config/routes.rb
Instalodger::Application.routes.draw do
  resources :listings

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  attr_accessible :active, :category, :description, :location, :name, :place, :price
  attr_accessible :image
  has_attached_file :image, :styles => { :medium => "320x320>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @listings }
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing = Listing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @listing }
    end
  end

  # GET /listings/new
  # GET /listings/new.json
  def new
    @listing = Listing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @listing }
    end
  end

  # GET /listings/1/edit
  def edit
    @listing = Listing.find(params[:id])
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(params[:listing])

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render json: @listing, status: :created, location: @listing }
      else
        format.html { render action: "new" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /listings/1
  # PUT /listings/1.json
  def update
    @listing = Listing.find(params[:id])

    respond_to do |format|
      if @listing.update_attributes(params[:listing])
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instalodger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :place %><br />
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>

<div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<div id="wrap">
	<div id="header">
		<a class="iconbtn" href="#"></a>
		<h4>Places</h4>
		<a class="filterbtn" href="#">Filter</a>	
	</div>
	<!-- header -->
	<div id="mainbody">		
			<div class="content listing">
				<ul>
<% @listings.each do |listing| %>									
  <a href="<%= url_for listing%>">
         <li class="<%= cycle('even', 'odd') -%>">
						<div class="one-fourth">
              <img src="<%= listing.location %>" width="160" height="160" >
            </div>
						<div class="two-fourth">
							<div class="inner">
                <h2><%= listing.name %></h2>
                <div class="split dark">Type: <%= listing.category %></div>
                <div class="split"><%= listing.place %></div>
								<div class="split">3 miles away </div>
							</div>
						</div>
						<div class="one-fourth">
							<div class="inner">
                <span class="price"><%= listing.price %></span>
							</div>
						</div>
            </li>
          </a>
<% end %> 
				</ul>
			</div>
	</div>
	<!-- end #mainbody -->
</div>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<div id="wrap">
  <div id="header">
    <a class="backbtn" href="/listings">Back</a>
    <h4><%= @listing.name %></h4>  
  </div>
  <!-- header -->
  <div id="mainbody">   
    <div class="content">
      <div class="imgwrap">
        <img src="<%=@listing.location %>" alt="" width="640" height="640">
        <span class="price-wt"><%= @listing.price %></span>
        <h4><a href="mailto:foo@bar.com">Contact Host</a></h4>
      </div>
      <div class="gmap">
        <img src="/assets/gmap.gif" alt="">
      </div>        
      <div class="details-content">
        <div class="inner">
          <div class="row-split">
            <div class="label-title">Type</div>
            <div class="con-des"><p><%= @listing.category %></p></div>
          </div>
          
          <div class="row-split">
            <div class="label-title">Description</div>
            <div class="con-des"><p>
              <%= @listing.description %> 
              </p></div>
          </div>
          
        </div>
      </div>
    </div>
  </div>
  <!-- end #mainbody -->
  
</div>